services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    tty: true
    stdin_open: true
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - backend