services:
# 公開用環境の起動
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - backend

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040