services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    tty: true
    stdin_open: true
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - backend
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040